---
- name: Provision SRV Dev
  hosts: all
  become: yes
  become_method: sudo
  remote_user: vagrant
  vars:
      ansible_ssh_private_key_file: C:\bloc3-slam\vagrant\.vagrant\machines\default\virtualbox\private_key
  tasks:
      - import_tasks: taches/confreseau.yml
      - import_tasks: taches/upgrade.yml
      - import_tasks: taches/lamp.yml
  
